# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        name: webauthn-demo
        cookie_lifetime: 0
        cookie_httponly: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    enabled_locales: [ 'fr', 'en']

    trusted_proxies: "%env(TRUSTED_PROXIES)%"
    trusted_hosts: "%env(TRUSTED_HOSTS)%"
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

when@test:
    framework:
        test: true
        http_client:
            mock_response_factory: App\Tests\MockClientCallback
        session:
            storage_factory_id: session.storage.factory.mock_file
        assets:
            json_manifest_path: ~
